[network]
relax-checks = true

[node]
session-timeout = "5"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "99.0", "platformName": "Linux"}'
max-sessions = 1
