#FROM selenium/standalone-chrome:4.1.2
FROM seleniarm/standalone-chromium:4.1.2-20220227
LABEL authors=Reputians

USER 1200

#RUN x11vnc -storepasswd prod-vnc-pass-dfdfdd-4699-975f-03ce33d5965c /home/seluser/.vnc/passwd

#====================================
# Scripts to run Selenium Standalone
#====================================
COPY node_chrome_vnc_s3/start-selenium-standalone.sh /opt/bin/start-selenium-standalone.sh

#==============================
# Supervisor configuration file
#==============================
COPY node_chrome_vnc_s3/selenium.conf /etc/supervisor/conf.d/

# Copying configuration script generator
COPY node_chrome_vnc_s3/generate_config /opt/bin/generate_config

USER root
RUN mkdir -p /python_server
RUN chown 1200 /python_server

COPY ./python_server /python_server

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install -y python3.8
RUN apt-get install -y python3-pip
RUN python3 --version
USER 1200

RUN cd /python_server && pip3 install -r requirements.txt

# Boolean value, maps "--relax-checks"
ENV SE_RELAX_CHECKS true

EXPOSE 4444
