version: '3'
services:
  selenium:
    image: 686143527223.dkr.ecr.ap-south-1.amazonaws.com/selenium-service:1.0.3
    container_name : kick-sele-arm
    hostname: kick-sele-arm
    environment:
#      - VNC_NO_PASSWORD=1
      - SE_NODE_SESSION_TIMEOUT=120
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "4444:4444"
      - "7900:7900"
      - "5900:5900"
    restart: always
    shm_size: '2gb'
