version: '3'
services:
  selenium:
    image: 686143527223.dkr.ecr.ap-south-1.amazonaws.com/selenium-service:1.0.1
    container_name : kick-sele
    hostname: kick-sele
    environment:
#      - VNC_NO_PASSWORD=1
      - SE_NODE_SESSION_TIMEOUT=120
    ports:
      - "4444:4444"
      - "7900:7900"
      - "5900:5900"
      - "8080:8080"
    restart: always
    shm_size: '2gb'
